language: node_js
node_js:
  - "14"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli@9

script:
  - ng lint
  - ng build --prod --base-href /restaurantes-app/
  - cd dist/restaurantes-app
  - cp index.html 404.html
  - cd ../..

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/restaurantes-app
  on:
    branch: master
